---
title: "2020 Predictor"
author: "Bilal Arif"
date: "01/11/2020"
output: html_document
---
```{r Load Packages}
library(ggplot2)
library(plyr)
```

```{r include=FALSE} 
# Import Data
DF1 <- read.csv("/Users/bilalarif/Desktop/NBA2019FD.csv")
DF2 <- read.csv("/Users/bilalarif/Desktop/NBA2018FD.csv")
DF3 <- read.csv("/Users/bilalarif/Desktop/NBA2017FD.csv")
DF4 <- read.csv("/Users/bilalarif/Desktop/NBA2016FD.csv")
DF5 <- read.csv("/Users/bilalarif/Desktop/NBA2015FD.csv")

# Combine Seasons into One Datafram
Data <- rbind(DF1, DF2, DF3, DF4, DF5)

# Clear Environment 
rm(DF1, DF2, DF3, DF4, DF5)

# Create a Full Game Spread using Second Half Spread
Data$`ATS` <- Data$H.H.Pts - Data$A.H.Pts + Data$A2S
Data$`HTS` <- Data$A.H.Pts - Data$H.H.Pts + Data$H2S

# Create Column of Spread Winner
for (i in 1:6150) {
  if(Data[i,49] + Data[i, 62] > Data[i, 50]){
    Data[i, 64] <- 'A'
  }else if(Data[i,49] + Data[i, 62] == Data[i, 50]){
    Data[i,64] <- 'D'
  }else{Data[i, 64] <- 'H'}}

# Rename Column of Spread Winner 
names(Data)[64] <- "SpreadWinner" 

# Remove A2S and H2S Columns
Data <- Data[, -c(59, 60)]

# Remove Home and Away Quarter 1 and 2 FGM/FGA/FGP
Data <- Data[, -c(1:3, 13:15, 25:27, 37:39)]

# Separate Home and Away Data
Home <- Data[,c( 1:18,39:40,43,49)]
Away <- Data[,c(19:36,41:42,44,48)]

# Create Linear Regression Model for Away Second Half Scoring
fit.away <- lm(A.2H.Scoring ~ . , data = Away)

summary(fit.away)
summary(fit.away)$coefficient
AM <- summary(fit.away)$coefficient

# Create Linear Regression Model for Home Second Half Scoring
fit.home <- lm(H.2H.Scoring ~ . , data = Home)

summary(fit.home)
summary(fit.home)$coefficient
HM <- summary(fit.home)$coefficient

# Create Predicted Second Half Scoring Columns
Away$`PSH` <- AM[1,1] + AM[2,1]*Away[,1] + AM[3,1]*Away[,2] + AM[4,1]*Away[,3] + AM[5,1]*Away[,4] + AM[6,1]*Away[,5] +
  AM[7,1]*Away[,6] + AM[8,1]*Away[,7] + AM[9,1]*Away[,8] + AM[10,1]*Away[,9] + AM[11,1]*Away[,10] + AM[12,1]*Away[,11] +
  AM[13,1]*Away[,12] + AM[14,1]*Away[,13] + AM[15,1]*Away[,14] + AM[16,1]*Away[,15] + AM[17,1]*Away[,16] + 
  AM[18,1]*Away[,17] + AM[19,1]*Away[,18] + AM[20,1]*Away[,19] + AM[21,1]*Away[,20] + AM[22,1]*Away[,22] 

Home$`PSH` <- HM[1,1] + HM[2,1]*Home[,1] + HM[3,1]*Home[,2] + HM[4,1]*Home[,3] + HM[5,1]*Home[,4] + HM[6,1]*Home[,5] +
  HM[7,1]*Home[,6] + HM[8,1]*Home[,7] + HM[9,1]*Home[,8] + HM[10,1]*Home[,9] + HM[11,1]*Home[,10] + HM[12,1]*Home[,11] +
  HM[13,1]*Home[,12] + HM[14,1]*Home[,13] + HM[15,1]*Home[,14] + HM[16,1]*Home[,15] + HM[17,1]*Home[,16] + 
  HM[18,1]*Home[,17] + HM[19,1]*Home[,18] + HM[20,1]*Home[,19] + HM[21,1]*Home[,20] + HM[22,1]*Home[,22]

# Create New Data Set to View Results
Viewing <- Data[,c(37:38,48:50, 45:46)]
Viewing$`APSH` <- Away$PSH
Viewing$`HPSH` <- Home$PSH
Viewing$`APF` <- Viewing$A.H.Pts + Viewing$APSH
Viewing$`HPF` <- Viewing$H.H.Pts + Viewing$HPSH

for (i in 1:6150) {
  if(Viewing[i,10] + Viewing[i, 3] > Viewing[i,11]){
    Viewing[i, 12] <- 'A'
  }else if(Viewing[i,10] + Viewing[i, 3] == Viewing[i,11]){
    Viewing[i, 12] <- 'D'
  }else{Viewing[i, 12] <- 'H' }
}

# Remove Observations with Draws
Viewing <- Viewing[Viewing$SpreadWinner != 'D', ]

# Create a Column which Gives 0/1 for Inaccurate/Accurate Predictions
for (i in 1:nrow(Viewing)) {
  if(Viewing[i,5] == Viewing[i,12]){
    Viewing[i,13] <- 1
    }else{Viewing[i,13] <- 0}
  }

# Check Results
Right <- sum(Viewing$V13)
Num <- nrow(Viewing)
Wrong <- Num - Right
PercRight <- Right/Num

Showing <- Viewing[, c(3,13)]
Showing$V13 <- factor(Viewing$V13)
Showing$ATS <- factor(Viewing$ATS)
Showing$HTS <- factor(Viewing$HTS)
Showing <- arrange(Showing, ATS, V13)
Show <-with(Showing, table(ATS, V13))
Show <- data.frame(Show)
names(Show)[3] <- "Yup"
Show <- arrange(Show, ATS, V13)
Show <- ddply(Show, "ATS", transform, label_ypos=cumsum(Yup))
Show$label_ypos <- Show$label_ypos - 5

ggplot(Show, aes(x = ATS, y = Yup, fill = V13)) + 
  geom_bar(stat = "identity") +
  geom_text(aes(y = label_ypos, label = Yup), color="black", size=3.5) +
  scale_fill_brewer(palette = "Set1") 
```

